import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { AiRequestBodySchema } from "@/lib/schemas";
import { rateLimiter } from "@/lib/rateLimit";
import { agentGraph } from "@/lib/agentGraph";
import { ChatMessage, LocationDetails } from "@/types";

if (process.env.NODE_ENV === "development") {
  process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
}

export async function POST(request: NextRequest) {
  // 1. Get Client IP Address for Rate Limiting
  const ip = request.headers.get("x-forwarded-for") || "127.0.0.1";

  // Limit: max 30 requests per IP per hour
  const rateLimitResult = rateLimiter(ip, 30, 60 * 60 * 1000);
  if (!rateLimitResult.success) {
    console.warn(`Rate limit exceeded for IP: ${ip}`);
    return NextResponse.json(
      { error: "Too many requests. Please try again later.", message: "Rate limit exceeded (30 messages/hr). Take a break!" },
      { status: 429 }
    );
  }

  // 2. Validate Request Body
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON request body" }, { status: 400 });
  }

  const validation = AiRequestBodySchema.safeParse(body);
  if (!validation.success) {
    return NextResponse.json(
      { error: "Invalid parameters in request body", details: validation.error.flatten() },
      { status: 400 }
    );
  }

  const { message, history, context, itinerary, dayAnchors } = validation.data;

  // 3. Check Gemini API Configuration
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.error("Missing GEMINI_API_KEY environment variable on the server");
    return NextResponse.json({ error: "Server API configuration missing" }, { status: 500 });
  }

  try {
    // 4. Map request payload to state
    const mappedHistory: ChatMessage[] = (history || []).map((h, index) => ({
      id: `hist-${index}-${Date.now()}`,
      role: h.role,
      text: h.text,
      timestamp: Date.now() - ((history?.length || 0) - index) * 1000,
    }));
    
    mappedHistory.push({
      id: `msg-${Date.now()}`,
      role: "user",
      text: message,
      timestamp: Date.now(),
    });

    const locationState: LocationDetails | null = context ? {
      coords: context.coords || null,
      cityName: context.cityName || null,
      permissionState: "granted",
    } : null;

    const parsedAnchors: Record<number, string> = {};
    if (dayAnchors) {
      for (const [key, value] of Object.entries(dayAnchors)) {
        parsedAnchors[Number(key)] = value;
      }
    }

    // 5. Invoke LangGraph
    const finalState = await agentGraph.invoke({
      messages: mappedHistory,
      itinerary: itinerary || null,
      location: locationState,
      weather: context?.weather || null,
      conflicts: [],
      loopCount: 0,
      routingTarget: "classifier",
      response: "",
      dayAnchors: parsedAnchors,
    });

    const responseText = finalState.response || "No response generated by agent graph.";

    // 6. Return response stream as ReadableStream
    const responseStream = new ReadableStream({
      async start(controller) {
        try {
          controller.enqueue(new TextEncoder().encode(responseText));
          controller.close();
        } catch (err) {
          console.error("Response stream error:", err);
          controller.error(err);
        }
      },
    });

    return new NextResponse(responseStream, {
      headers: {
        "Content-Type": "text/event-stream; charset=utf-8",
        "Cache-Control": "no-cache, no-transform",
        "Connection": "keep-alive",
      },
    });
  } catch (error) {
    console.error("LangGraph flow failed:", error);
    return NextResponse.json({ error: "Failed to connect to AI assistant" }, { status: 500 });
  }
}
