import type { ItineraryDay } from "@/types";

/** Jun 2026 Lake Garda teen trip — Monzambano base, 10:00–19:00 day trips. */
export const DEFAULT_ITALY_ITINERARY: ItineraryDay[] = [
  {
    dayNumber: 1,
    date: "Jun 25 – Milan Arrival",
    activities: [
      {
        id: "a1",
        time: "18:55",
        title: "Flight 6404 Departs TLV",
        description: "Depart Tel Aviv (TLV) on flight 6404. Estimated flight time ~4 hrs.",
        locationName: "Tel Aviv",
      },
      {
        id: "a2",
        time: "22:10",
        title: "Arrive Malpensa (MXP)",
        description: "Land at Milan Malpensa Airport. Proceed to baggage claim and head to accommodation in Ferno.",
        locationName: "Malpensa, Milan",
      },
      {
        id: "a3",
        time: "23:00",
        title: "Check-in: Malpensa Jacuzzi House",
        description: "Self-check-in via lockbox — code & video instructions sent via WhatsApp. Accommodation for 7 adults in Ferno, right next to the airport.",
        locationName: "Ferno, Milan",
      },
    ],
  },
  {
    dayNumber: 2,
    date: "Jun 26 – Car Pickup & Drive to Monzambano",
    activities: [
      {
        id: "a4",
        time: "10:00",
        title: "Car Rental Pickup – Centauro",
        description: "Pick up rental car at Malpensa Airport with Centauro. Group E2 — Hyundai Kona or similar. Check fuel level, note any existing damage, confirm drop-off instructions.",
        locationName: "Malpensa Airport",
      },
      {
        id: "a5",
        time: "11:30",
        title: "Drive to Monzambano",
        description: "Scenic drive ~1.5 hrs from Malpensa to Monzambano on Lake Garda. Follow A8/A4 motorway.",
        locationName: "Monzambano, Lake Garda",
      },
      {
        id: "a6",
        time: "13:00",
        title: "Check-in: Villa Eunice",
        description: "Home base for 7 nights (Jun 26 – Jul 2). Villa for 7 adults. ⚠️ No smoke/CO detectors reported — consider bringing a portable one.",
        locationName: "Monzambano, Lake Garda",
      },
      {
        id: "a6b",
        time: "15:00",
        title: "Lake Swim & Village Stroll",
        description: "Easy afternoon: short walk through Monzambano castle ruins, then swim at the lake shore (~45 min walking total).",
        locationName: "Monzambano",
        lat: 45.337,
        lng: 10.528,
      },
      {
        id: "a6c",
        time: "19:00",
        title: "Welcome Dinner",
        description: "Trattoria del Ponte — lake fish and local pasta. Alternative: Osteria del Moro in the village.",
        locationName: "Monzambano",
        lat: 45.337,
        lng: 10.528,
      },
    ],
  },
  {
    dayNumber: 3,
    date: "Jun 27 – Lake Boat & Rimbalzello",
    activities: [
      {
        id: "a7",
        time: "10:00",
        title: "Desenzano Harbor & Gelato",
        description: "Stroll the harbor and promenade (~30 min). Gelato stop: Gelateria San Rocco.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
      {
        id: "a8",
        time: "11:00",
        title: "Self-Drive Boat Rental (2 hrs)",
        description: "Rent a small boat (no license, up to 40 HP) for lake views and swimming stops. Book ahead for 11:00 slot.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
      {
        id: "a8b",
        time: "13:30",
        title: "Lunch — Ristorante Pace",
        description: "Fresh lake fish, risotto, and trout specialties on the Desenzano waterfront.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
      {
        id: "a9",
        time: "15:30",
        title: "Rimbalzello Adventure Park",
        description: "Treetop ropes, zip lines, and Tibetan bridges with lake views (~2.5 hrs). Nature + adventure combo.",
        locationName: "Manerba del Garda",
        lat: 45.492,
        lng: 10.6055,
      },
      {
        id: "a9b",
        time: "18:30",
        title: "Return to Villa Eunice",
        description: "Relax at the villa — pool, garden, or light grocery run for tomorrow.",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 4,
    date: "Jun 28 – Verona & Natura Viva Safari",
    activities: [
      {
        id: "a10",
        time: "10:00",
        title: "Verona Arena",
        description: "Visit the 1st-century Roman amphitheater (~1 hr). Park near Piazza Bra.",
        locationName: "Verona",
        lat: 45.439,
        lng: 10.9944,
      },
      {
        id: "a11",
        time: "11:45",
        title: "Historic Center & Light Shopping",
        description: "Piazza delle Erbe, Juliet's balcony (street view), Via Mazzini shopping (~1.5 hrs walking).",
        locationName: "Verona",
        lat: 45.439,
        lng: 10.9944,
      },
      {
        id: "a12",
        time: "13:00",
        title: "Lunch — Trattoria Al Pompiere",
        description: "Classic Verona grill — pollo alla griglia and local wines. Alternative: Osteria da Dante.",
        locationName: "Verona",
        lat: 45.443,
        lng: 10.998,
      },
      {
        id: "a12b",
        time: "14:30",
        title: "Natura Viva Safari Park",
        description: "Safari drive and zoo — strong teen appeal (~3 hrs). On the way back toward the lake.",
        locationName: "Bussolengo",
        lat: 45.4431,
        lng: 10.8706,
      },
      {
        id: "a12c",
        time: "18:30",
        title: "Return to Monzambano",
        description: "Drive back to Villa Eunice (~45 min).",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 5,
    date: "Jun 29 – Sirmione & Aquaria Spa",
    activities: [
      {
        id: "a13",
        time: "10:00",
        title: "Sirmione — Scaligero Castle",
        description: "Drive 25 min. Park outside old town walls. Castle visit ~45 min, then old-town stroll and gelato (~30 min).",
        locationName: "Sirmione",
        lat: 45.4928,
        lng: 10.6085,
      },
      {
        id: "a14",
        time: "12:30",
        title: "Lunch — Locanda al Bersagliere",
        description: "Near the castle — lake views. Alternative: La Roccia on the water.",
        locationName: "Sirmione",
        lat: 45.491,
        lng: 10.607,
      },
      {
        id: "a15",
        time: "14:00",
        title: "Aquaria Thermal Spa",
        description: "Lakeside thermal pools (~3 hrs). Pre-booked for the group — confirm reservation at check-in.",
        locationName: "Sirmione",
        lat: 45.4903,
        lng: 10.6084,
      },
      {
        id: "a15b",
        time: "18:00",
        title: "Return to Villa Eunice",
        description: "Easy drive back to Monzambano.",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 6,
    date: "Jun 30 – Gardaland",
    activities: [
      {
        id: "a16",
        time: "09:30",
        title: "Depart for Gardaland",
        description: "Leave early — park opens 10:00. ~45 min drive from Monzambano. Consider Fast Pass on busy days.",
        locationName: "Castelnuovo del Garda",
        lat: 45.4542,
        lng: 10.7137,
      },
      {
        id: "a17",
        time: "10:00",
        title: "Gardaland Theme Park",
        description: "Full day — roller coasters, water rides, and SEA LIFE aquarium. Lunch inside the park ~12:30.",
        locationName: "Gardaland",
        lat: 45.4542,
        lng: 10.7137,
      },
      {
        id: "a18",
        time: "18:30",
        title: "Return to Villa Eunice",
        description: "Drive back — relaxed villa dinner or pizza night.",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 7,
    date: "Jul 1 – Monte Baldo Nature Day",
    activities: [
      {
        id: "a19",
        time: "10:00",
        title: "Drive to Malcesine",
        description: "North shore ~1 hr 15 min. Quick harbor stroll and gelato (~30 min walking).",
        locationName: "Malcesine",
        lat: 45.7628,
        lng: 10.8115,
      },
      {
        id: "a20",
        time: "11:45",
        title: "Monte Baldo Cable Car",
        description: "Rotating cable car to the summit — panoramic views over Lake Garda.",
        locationName: "Malcesine",
        lat: 45.7634,
        lng: 10.8123,
      },
      {
        id: "a20b",
        time: "12:30",
        title: "Summit Lunch — Rifugio Altissimo",
        description: "Simple mountain lunch with views. Pre-lunch option: Ristorante Vecchia Malcesine in town.",
        locationName: "Monte Baldo",
        lat: 45.816,
        lng: 10.852,
      },
      {
        id: "a20c",
        time: "13:30",
        title: "Easy Summit Walk (~2 hrs max)",
        description: "Sentiero panoramico — gentle paths, no long trek. Optional tandem paragliding 15:30 (age 16+, book ahead).",
        locationName: "Monte Baldo",
        lat: 45.816,
        lng: 10.852,
      },
      {
        id: "a20d",
        time: "17:00",
        title: "Cable Car Down & Return",
        description: "Gelato in Malcesine, then drive back — home ~19:00.",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 8,
    date: "Jul 2 – Borghetto & Sigurtà Gardens",
    activities: [
      {
        id: "a21",
        time: "10:00",
        title: "Borghetto sul Mincio",
        description: "Medieval watermill village — riverside walk (~1 hr). One of Italy's most scenic hamlets, 15 min from villa.",
        locationName: "Borghetto sul Mincio",
        lat: 45.3533,
        lng: 10.7378,
      },
      {
        id: "a22",
        time: "12:00",
        title: "Lunch — Taverna del Silenzio",
        description: "Book ahead! Famous Tortellini di Valeggio ('Love Knots') in Borghetto.",
        locationName: "Borghetto sul Mincio",
        lat: 45.353,
        lng: 10.735,
      },
      {
        id: "a23",
        time: "13:30",
        title: "Parco Giardino Sigurtà",
        description: "Flat garden paths, flowers, and shade (~2 hrs walking). Gentle nature day close to base.",
        locationName: "Valeggio sul Mincio",
        lat: 45.3628,
        lng: 10.7347,
      },
      {
        id: "a23b",
        time: "16:30",
        title: "Villa Relax & Pre-packing",
        description: "Pool, garden, and start organizing luggage for Milan transition tomorrow.",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 9,
    date: "Jul 3 – Shopping & Milan Transition",
    activities: [
      {
        id: "a24",
        time: "09:30",
        title: "Check-out: Villa Eunice",
        description: "Check out of Villa Eunice. Ensure all items are packed, key returned, and loaded into the rental car.",
        locationName: "Monzambano",
      },
      {
        id: "a25",
        time: "10:00",
        title: "Serravalle Designer Outlet",
        description: "Drive ~1 hr 45 min. Shopping ~3 hrs — Nike, Adidas, Prada, Gucci outlets. Lunch at outlet food court.",
        locationName: "Serravalle Scrivia",
        lat: 44.6533,
        lng: 8.7847,
      },
      {
        id: "a26",
        time: "15:00",
        title: "Drive to Milan & Check-in",
        description: "Continue to Milan (~1 hr 15 min). ⚠️ ZTL / Area C: pay €7.50 entry fee if entering before 19:30 on Friday.",
        locationName: "Milan",
        lat: 45.464,
        lng: 9.19,
      },
      {
        id: "a27",
        time: "18:00",
        title: "Car Return – Centauro (Milano)",
        description: "Return rental car (Group E2) to Centauro at Via Copernico 28/30, 20125 Milano by 19:00 deadline. Fuel full.",
        locationName: "Via Copernico 28/30, Milan",
      },
      {
        id: "a28",
        time: "20:00",
        title: "Farewell Dinner in Milan",
        description: "Trattoria del Nuovo Macello (steak) or Spontini pizza. Navigli district for evening drinks.",
        locationName: "Milan",
        lat: 45.452,
        lng: 9.175,
      },
    ],
  },
  {
    dayNumber: 10,
    date: "Jul 4 – Departure",
    activities: [
      {
        id: "a29",
        time: "08:30",
        title: "Check-out: Splendido Ultimo Piano",
        description: "Check out of the Milan apartment. Proceed to Milan Malpensa Airport (MXP) via taxi or Malpensa Express train (~50 min).",
        locationName: "Milan",
      },
      {
        id: "a30",
        time: "10:05",
        title: "Arrive Malpensa Airport – Check-in",
        description: "Arrive at MXP 3 hours before your flight to complete check-in, baggage drop, and security screening.",
        locationName: "Malpensa Airport",
      },
      {
        id: "a31",
        time: "13:05",
        title: "Flight 6403 Departs MXP → TLV",
        description: "Board flight 6403 departing MXP at 13:05. Scheduled arrival in Tel Aviv (TLV) at 18:00.",
        locationName: "Malpensa Airport",
      },
    ],
  },
];
