import type { ItineraryDay } from "@/types";

/** Jun 2026 Lake Garda teen trip — Desenzano del Garda base, 10:00–19:00 day trips. */
export const DEFAULT_ITALY_ITINERARY: ItineraryDay[] = [
  {
    dayNumber: 1,
    date: "Jun 25 – Milan Arrival",
    activities: [
      {
        id: "a1",
        time: "18:55",
        title: "Flight 6404 Departs TLV (Wizz Air W5 6404)",
        description: "Depart Tel Aviv (TLV) 18:55 — arrive Milan Malpensa (MXP) 22:10. Duration ~4h 15m. Confirmation PQGFPN.",
        locationName: "Tel Aviv",
      },
      {
        id: "a2",
        time: "22:10",
        title: "Arrive Malpensa (MXP)",
        description: "Land at Milan Malpensa Airport. Proceed to baggage claim and head to accommodation in Ferno.",
        locationName: "Malpensa, Milan",
      },
      {
        id: "a3",
        time: "23:00",
        title: "Check-in: Malpensa Jacuzzi House",
        description: "Self-check-in via lockbox — code & video instructions sent via WhatsApp. Accommodation for 7 adults in Ferno, right next to the airport.",
        locationName: "Ferno, Milan",
      },
    ],
  },
  {
    dayNumber: 2,
    date: "Jun 26 – Lakeside or Bergamo & Desenzano",
    activities: [
      {
        id: "a4",
        time: "10:00",
        title: "Car Rental Pickup – Centauro",
        description: "Pick up rental car at Malpensa Airport with Centauro. Group E2 — Hyundai Kona or similar. Check fuel level, note any existing damage, confirm drop-off instructions.",
        locationName: "Malpensa Airport",
      },
      {
        id: "a5",
        time: "10:30",
        title: "Drive toward Lake Garda",
        description: "A8 → A4 toward Bergamo and Garda. Optional 15 min Autogrill break on the motorway.",
        locationName: "En route",
      },
      {
        id: "a5b",
        time: "12:00",
        title: "Stop — Lungolago Virgilio OR Bergamo Upper Town",
        description:
          "Group picks one en-route stop (see Day guide). Option A: lakeside walk at Lungolago Virgilio, Peschiera (~45–60 min) + pizza/panini lunch. Option B: funicular to Bergamo upper town — Old Square, cathedral, Venetian walls (~60–90 min) + pizza/panini lunch.",
        locationName: "En route to Lake Garda",
      },
      {
        id: "a5c",
        time: "14:30",
        title: "Drive to Desenzano del Garda",
        description: "Continue to Villa Bella Desenzano (~45–75 min from the stop). VRBO check-in from 17:00 — arrive with time to unload.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
      {
        id: "a6",
        time: "17:00",
        title: "Check-in: Villa Bella Desenzano",
        description:
          "Home base for 7 nights (Jun 26 – Jul 3). VRBO HA-HC6RCW · property 10207760 · 3 adults + 4 children. €98 balance due at property. Check-in instructions sent ~Jun 23.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
      {
        id: "a6b",
        time: "18:30",
        title: "Waterfront Stroll",
        description: "Easy evening: short walk along Desenzano lungolago and old harbour (~30 min).",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
      {
        id: "a6c",
        time: "20:00",
        title: "Welcome Dinner — Ristorante Pace",
        description: "Lake fish and risotto on the waterfront. Alternatives: lakeside pizzerias along Via Guglielmo Marconi.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
        sourceAttractionId: "bank-dining-pace",
      },
    ],
  },
  {
    dayNumber: 3,
    date: "Jun 27 – Castellaro, Borghetto & Sigurta Gardens",
    activities: [
      {
        id: "a7",
        time: "09:00",
        title: "Castellaro Lagusello",
        description: "Medieval hamlet and small lake loop walk (~20–30 min). One of Italy's most beautiful villages — ~35 min drive from Desenzano.",
        locationName: "Castellaro Lagusello",
        lat: 45.368,
        lng: 10.528,
      },
      {
        id: "a7b",
        time: "10:15",
        title: "Borghetto Village",
        description: "Watermills on the Mincio River — riverside village walk (~1 hr). Visconti Bridge.",
        locationName: "Borghetto sul Mincio",
        lat: 45.3533,
        lng: 10.7378,
        sourceAttractionId: "bank-borghetto",
      },
      {
        id: "a7c",
        time: "12:00",
        title: "Lunch — Taverna del Silenzio (book ahead)",
        description: "Book ahead! Famous Valeggio-style tortellini in Borghetto.",
        locationName: "Borghetto sul Mincio",
        lat: 45.353,
        lng: 10.735,
        sourceAttractionId: "bank-dining-silenzio",
      },
      {
        id: "a7d",
        time: "13:30",
        title: "Sigurta Garden Park",
        description: "Flat garden paths, flowers, and shade (~2 hrs walking). Gentle nature day — ~20 min from Borghetto.",
        locationName: "Valeggio sul Mincio",
        lat: 45.3628,
        lng: 10.7347,
        sourceAttractionId: "bank-sigurta",
      },
      {
        id: "a7e",
        time: "16:30",
        title: "Return to Villa Bella",
        description: "Pool, garden, or easy evening at the villa.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
    ],
  },
  {
    dayNumber: 4,
    date: "Jun 28 – Manerba Boat & Rocca Walk",
    activities: [
      {
        id: "a8boat",
        time: "09:30",
        title: "Manerba — Self-Drive Boat Rental (2 hrs)",
        description: "Rent a small family boat from Manerba marina (no license, up to 40 HP). Book ahead; swim stops on the lake. ~40 min drive from Desenzano.",
        locationName: "Manerba del Garda",
        lat: 45.492,
        lng: 10.6055,
        sourceAttractionId: "bank-manerba-boat",
      },
      {
        id: "a8rocca",
        time: "12:00",
        title: "Manerba Rocca Natural Park",
        description: "Clifftop trails and lake panoramas (~1.5–2 hr walk). Archaeological park on the same peninsula.",
        locationName: "Manerba del Garda",
        lat: 45.492,
        lng: 10.6055,
      },
      {
        id: "a8lunch",
        time: "13:30",
        title: "Lunch — Lido Azzurro or lakeside pizzeria",
        description: "Waterfront pizza and lake fish. Optional harbor stroll after — see Day guide.",
        locationName: "Manerba del Garda",
        lat: 45.492,
        lng: 10.6055,
      },
      {
        id: "a8ret",
        time: "17:00",
        title: "Return to Villa Bella",
        description: "Easy evening at the villa.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
    ],
  },
  {
    dayNumber: 5,
    date: "Jun 29 – Gardaland",
    activities: [
      {
        id: "a16",
        time: "09:45",
        title: "Depart for Gardaland",
        description: "Park opens 10:00. ~20 min drive from Desenzano. Weekday visit — shorter queues than Saturday.",
        locationName: "Castelnuovo del Garda",
        lat: 45.4542,
        lng: 10.7137,
      },
      {
        id: "a17",
        time: "10:00",
        title: "Gardaland Theme Park",
        description: "Full day — roller coasters, water rides, and SEA LIFE aquarium. Lunch inside the park ~12:30.",
        locationName: "Gardaland",
        lat: 45.4542,
        lng: 10.7137,
        sourceAttractionId: "bank-gardaland",
      },
      {
        id: "a18",
        time: "18:30",
        title: "Return to Villa Bella",
        description: "Short drive back — relaxed villa dinner or pizza night.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
    ],
  },
  {
    dayNumber: 6,
    date: "Jun 30 – Verona (or Monte Baldo — see Day guide)",
    activities: [
      {
        id: "a10",
        time: "09:00",
        title: "Verona Arena",
        description: "Full Verona day (Option A). Group vote: Option B is Monte Baldo + Malcesine — see Day guide. Arena visit ~1 hr; park near Bra Square.",
        locationName: "Verona",
        lat: 45.439,
        lng: 10.9944,
        sourceAttractionId: "bank-verona-arena",
      },
      {
        id: "a11",
        time: "11:00",
        title: "Historic Center & Light Shopping",
        description: "Herbs Square (Piazza delle Erbe), Juliet's balcony (quick photo), Via Mazzini shopping (~1.5 hrs walking).",
        locationName: "Verona",
        lat: 45.439,
        lng: 10.9944,
      },
      {
        id: "a12",
        time: "12:30",
        title: "Lunch — Al Pompiere or pizza",
        description: "Classic Verona grill — grilled chicken. Alternative: Osteria da Dante or Pizzeria Du de Cope.",
        locationName: "Verona",
        lat: 45.443,
        lng: 10.998,
        sourceAttractionId: "bank-dining-pompiere",
      },
      {
        id: "a12b",
        time: "14:00",
        title: "Stone Bridge & Ice Cream",
        description: "Roman bridge (Ponte Pietra) and riverside stroll before drive home.",
        locationName: "Verona",
        lat: 45.439,
        lng: 10.9944,
      },
      {
        id: "a12c",
        time: "17:30",
        title: "Return to Desenzano",
        description: "Drive back to Villa Bella (~40 min).",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
    ],
  },
  {
    dayNumber: 7,
    date: "Jul 1 – CanevaWorld & Peschiera",
    activities: [
      {
        id: "a19",
        time: "09:45",
        title: "Depart for CanevaWorld",
        description: "Drive to Lazise resort area (~25 min). Heat-friendly water park day.",
        locationName: "Lazise",
        lat: 45.4817,
        lng: 10.7936,
      },
      {
        id: "a19b",
        time: "10:00",
        title: "CanevaWorld Aqua Paradise",
        description: "Extreme slides, wave pools, lazy river — full day until ~15:00. Lunch in park ~13:00.",
        locationName: "Lazise",
        lat: 45.4817,
        lng: 10.7936,
        sourceAttractionId: "bank-caneva-aqua",
      },
      {
        id: "a19c",
        time: "15:30",
        title: "Peschiera Harbor Walk",
        description: "Fortress walls, canals, and harbor stroll (~45 min) — same south-shore area.",
        locationName: "Peschiera del Garda",
        lat: 45.439,
        lng: 10.692,
        sourceAttractionId: "bank-peschiera",
      },
      {
        id: "a19d",
        time: "17:30",
        title: "Return to Villa Bella",
        description: "Short drive back to Desenzano.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
    ],
  },
  {
    dayNumber: 8,
    date: "Jul 2 – Sirmione & Aquaria Spa",
    activities: [
      {
        id: "a13",
        time: "10:00",
        title: "Sirmione — Scaliger Castle",
        description: "Castle visit ~45 min, then old-town stroll and ice cream (~30 min). ~15 min drive from Desenzano. Optional: Catullus Caves if time — see Day guide.",
        locationName: "Sirmione",
        lat: 45.4928,
        lng: 10.6085,
        sourceAttractionId: "bank-sirmione-castle",
      },
      {
        id: "a14",
        time: "12:15",
        title: "Lunch — La Roccia or San Lorenzo",
        description: "Casual lake lunch near the castle. Alternatives: Locanda al Bersagliere or San Lorenzo restaurant.",
        locationName: "Sirmione",
        lat: 45.491,
        lng: 10.607,
        sourceAttractionId: "bank-dining-bersagliere",
      },
      {
        id: "a15",
        time: "14:00",
        title: "Aquaria Thermal Spa",
        description: "Lakeside thermal pools (~3 hrs). Pre-booked for the group ✅ — confirm reservation at check-in.",
        locationName: "Sirmione",
        lat: 45.4903,
        lng: 10.6084,
        sourceAttractionId: "bank-aquaria-spa",
      },
      {
        id: "a15b",
        time: "18:00",
        title: "Return to Villa Bella",
        description: "Pre-packing for Milan transition tomorrow.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
    ],
  },
  {
    dayNumber: 9,
    date: "Jul 3 – Serravalle & Milan",
    activities: [
      {
        id: "a24",
        time: "09:30",
        title: "Check-out: Villa Bella Desenzano",
        description:
          "Check out before 10:00. Settle €98 balance if not yet paid. Ensure all items packed, keys returned, and loaded into the rental car.",
        locationName: "Desenzano del Garda",
        lat: 45.4711,
        lng: 10.5358,
      },
      {
        id: "a25",
        time: "10:00",
        title: "Serravalle Designer Outlet",
        description: "Drive ~1 hr 45 min. Shopping ~3 hrs — Nike, Adidas, Prada, Gucci outlets. Lunch at outlet food court.",
        locationName: "Serravalle Scrivia",
        lat: 44.6533,
        lng: 8.7847,
        sourceAttractionId: "bank-serravalle",
      },
      {
        id: "a26",
        time: "15:00",
        title: "Drive to Milan & Check-in",
        description: "Continue to Milan (~1 hr 15 min). ⚠️ ZTL / Area C: pay €7.50 entry fee if entering before 19:30 on Friday.",
        locationName: "Milan",
        lat: 45.464,
        lng: 9.19,
      },
      {
        id: "a27",
        time: "18:00",
        title: "Car Return – Centauro (Milano)",
        description: "Return rental car (Group E2) to Centauro at Via Copernico 28/30, 20125 Milano by 19:00 deadline. Fuel full.",
        locationName: "Via Copernico 28/30, Milan",
      },
      {
        id: "a28",
        time: "20:00",
        title: "Farewell Dinner in Milan",
        description: "Steak at Nuovo Macello or Spontini pizza. Navigli canals for evening drinks.",
        locationName: "Milan",
        lat: 45.452,
        lng: 9.175,
        sourceAttractionId: "bank-dining-macello",
      },
    ],
  },
  {
    dayNumber: 10,
    date: "Jul 4 – Departure",
    activities: [
      {
        id: "a29",
        time: "08:30",
        title: "Check-out: Splendido Ultimo Piano",
        description: "Check out of the Milan apartment. Proceed to Milan Malpensa Airport (MXP) via taxi or Malpensa Express train (~50 min).",
        locationName: "Milan",
      },
      {
        id: "a30",
        time: "10:05",
        title: "Arrive Malpensa Airport – Check-in",
        description: "Arrive at MXP 3 hours before your flight to complete check-in, baggage drop, and security screening.",
        locationName: "Malpensa Airport",
      },
      {
        id: "a31",
        time: "13:05",
        title: "Flight 6403 Departs MXP → TLV (Wizz Air W4 6403)",
        description: "Depart Milan Malpensa (MXP) 13:05 — arrive Tel Aviv (TLV) 18:00. Duration ~3h 55m. Confirmation PQGFPN.",
        locationName: "Malpensa Airport",
      },
    ],
  },
];
