import type { ItineraryDay } from "@/types";

/** Jun 2026 Lake Garda teen trip — Monzambano base, 10:00–19:00 day trips. */
export const DEFAULT_ITALY_ITINERARY: ItineraryDay[] = [
  {
    dayNumber: 1,
    date: "Jun 25 – Milan Arrival",
    activities: [
      {
        id: "a1",
        time: "18:55",
        title: "Flight 6404 Departs TLV",
        description: "Depart Tel Aviv (TLV) on flight 6404. Estimated flight time ~4 hrs.",
        locationName: "Tel Aviv",
      },
      {
        id: "a2",
        time: "22:10",
        title: "Arrive Malpensa (MXP)",
        description: "Land at Milan Malpensa Airport. Proceed to baggage claim and head to accommodation in Ferno.",
        locationName: "Malpensa, Milan",
      },
      {
        id: "a3",
        time: "23:00",
        title: "Check-in: Malpensa Jacuzzi House",
        description: "Self-check-in via lockbox — code & video instructions sent via WhatsApp. Accommodation for 7 adults in Ferno, right next to the airport.",
        locationName: "Ferno, Milan",
      },
    ],
  },
  {
    dayNumber: 2,
    date: "Jun 26 – Bergamo & Monzambano",
    activities: [
      {
        id: "a4",
        time: "10:00",
        title: "Car Rental Pickup – Centauro",
        description: "Pick up rental car at Malpensa Airport with Centauro. Group E2 — Hyundai Kona or similar. Check fuel level, note any existing damage, confirm drop-off instructions.",
        locationName: "Malpensa Airport",
      },
      {
        id: "a5",
        time: "10:30",
        title: "Drive toward Lake Garda",
        description: "A8 → A4 toward Bergamo and Garda. Optional 15 min Autogrill break on the motorway.",
        locationName: "En route",
      },
      {
        id: "a5b",
        time: "12:00",
        title: "Stop — Bergamo Città Alta",
        description: "Funicular up to Città Alta — Piazza Vecchia, basilica, Venetian walls, Campanone tower (~60–90 min). Lunch: La Bruschetta or Pizzeria Sant'Angelo.",
        locationName: "Bergamo",
        lat: 45.704,
        lng: 9.662,
      },
      {
        id: "a5c",
        time: "13:30",
        title: "Drive to Monzambano",
        description: "Continue to Villa Eunice (~1.5 hrs from Bergamo). Confirm late check-in ~15:00 if needed.",
        locationName: "Monzambano, Lake Garda",
      },
      {
        id: "a6",
        time: "15:00",
        title: "Check-in: Villa Eunice",
        description: "Home base for 7 nights (Jun 26 – Jul 2). Villa for 7 adults. ⚠️ No smoke/CO detectors reported — consider bringing a portable one.",
        locationName: "Monzambano, Lake Garda",
      },
      {
        id: "a6b",
        time: "16:30",
        title: "Lake Swim & Village Stroll",
        description: "Easy afternoon: short walk through Monzambano castle ruins, then swim at the lake shore (~45 min walking total).",
        locationName: "Monzambano",
        lat: 45.337,
        lng: 10.528,
      },
      {
        id: "a6c",
        time: "19:00",
        title: "Welcome Dinner — Trattoria del Ponte",
        description: "Lake fish and local pasta. Alternative: Osteria del Moro in the village.",
        locationName: "Monzambano",
        lat: 45.337,
        lng: 10.528,
        sourceAttractionId: "bank-dining-ponte",
      },
    ],
  },
  {
    dayNumber: 3,
    date: "Jun 27 – Castellaro, Borghetto & Sigurtà",
    activities: [
      {
        id: "a7",
        time: "09:30",
        title: "Castellaro Lagusello",
        description: "Medieval hamlet and small lake loop walk (~20–30 min). One of Italy's borghi più belli — 10 min from villa.",
        locationName: "Castellaro Lagusello",
        lat: 45.368,
        lng: 10.528,
      },
      {
        id: "a7b",
        time: "10:15",
        title: "Borghetto sul Mincio",
        description: "Watermills on the Mincio — riverside village walk (~1 hr). Ponte Visconteo.",
        locationName: "Borghetto sul Mincio",
        lat: 45.3533,
        lng: 10.7378,
        sourceAttractionId: "bank-borghetto",
      },
      {
        id: "a7c",
        time: "12:00",
        title: "Lunch — Taverna del Silenzio",
        description: "Book ahead! Famous Tortellini di Valeggio in Borghetto.",
        locationName: "Borghetto sul Mincio",
        lat: 45.353,
        lng: 10.735,
        sourceAttractionId: "bank-dining-silenzio",
      },
      {
        id: "a7d",
        time: "13:30",
        title: "Parco Giardino Sigurtà",
        description: "Flat garden paths, flowers, and shade (~2 hrs walking). Gentle nature day close to base.",
        locationName: "Valeggio sul Mincio",
        lat: 45.3628,
        lng: 10.7347,
        sourceAttractionId: "bank-sigurta",
      },
      {
        id: "a7e",
        time: "16:30",
        title: "Return to Villa Eunice",
        description: "Pool, garden, or easy evening at the villa.",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 4,
    date: "Jun 28 – Verona (or Monte Baldo — see Day guide)",
    activities: [
      {
        id: "a10",
        time: "09:00",
        title: "Verona Arena",
        description: "Full Verona day (Option A). Group vote: Option B is Monte Baldo + Malcesine — see Day guide. Arena visit ~1 hr; park near Piazza Bra.",
        locationName: "Verona",
        lat: 45.439,
        lng: 10.9944,
        sourceAttractionId: "bank-verona-arena",
      },
      {
        id: "a11",
        time: "11:00",
        title: "Historic Center & Light Shopping",
        description: "Piazza delle Erbe, Juliet's balcony (quick photo), Via Mazzini shopping (~1.5 hrs walking).",
        locationName: "Verona",
        lat: 45.439,
        lng: 10.9944,
      },
      {
        id: "a12",
        time: "12:30",
        title: "Lunch — Trattoria Al Pompiere",
        description: "Classic Verona grill — pollo alla griglia. Alternative: Osteria da Dante or Pizzeria Du de Cope.",
        locationName: "Verona",
        lat: 45.443,
        lng: 10.998,
        sourceAttractionId: "bank-dining-pompiere",
      },
      {
        id: "a12b",
        time: "14:00",
        title: "Ponte Pietra & Gelato",
        description: "Roman bridge and riverside stroll before drive home.",
        locationName: "Verona",
        lat: 45.439,
        lng: 10.9944,
      },
      {
        id: "a12c",
        time: "17:30",
        title: "Return to Monzambano",
        description: "Drive back to Villa Eunice (~45 min).",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 5,
    date: "Jun 29 – Gardaland",
    activities: [
      {
        id: "a16",
        time: "09:30",
        title: "Depart for Gardaland",
        description: "Leave early — park opens 10:00. ~45 min drive from Monzambano. Weekday visit — shorter queues than Saturday.",
        locationName: "Castelnuovo del Garda",
        lat: 45.4542,
        lng: 10.7137,
      },
      {
        id: "a17",
        time: "10:00",
        title: "Gardaland Theme Park",
        description: "Full day — roller coasters, water rides, and SEA LIFE aquarium. Lunch inside the park ~12:30.",
        locationName: "Gardaland",
        lat: 45.4542,
        lng: 10.7137,
        sourceAttractionId: "bank-gardaland",
      },
      {
        id: "a18",
        time: "18:30",
        title: "Return to Villa Eunice",
        description: "Drive back — relaxed villa dinner or pizza night.",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 6,
    date: "Jun 30 – Sirmione & Aquaria Spa",
    activities: [
      {
        id: "a13",
        time: "10:00",
        title: "Sirmione — Scaligero Castle",
        description: "Castle visit ~45 min, then old-town stroll and gelato (~30 min). Optional: Grotte di Catullo if time — see Day guide.",
        locationName: "Sirmione",
        lat: 45.4928,
        lng: 10.6085,
        sourceAttractionId: "bank-sirmione-castle",
      },
      {
        id: "a14",
        time: "12:15",
        title: "Lunch — Locanda al Bersagliere",
        description: "Near the castle — lake views. Alternative: La Roccia or Trattoria San Lorenzo.",
        locationName: "Sirmione",
        lat: 45.491,
        lng: 10.607,
        sourceAttractionId: "bank-dining-bersagliere",
      },
      {
        id: "a15",
        time: "14:00",
        title: "Aquaria Thermal Spa",
        description: "Lakeside thermal pools (~3 hrs). Pre-booked for the group — confirm reservation at check-in.",
        locationName: "Sirmione",
        lat: 45.4903,
        lng: 10.6084,
        sourceAttractionId: "bank-aquaria-spa",
      },
      {
        id: "a15b",
        time: "18:00",
        title: "Return to Villa Eunice",
        description: "Easy drive back to Monzambano.",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 7,
    date: "Jul 1 – CanevaWorld & Peschiera",
    activities: [
      {
        id: "a19",
        time: "09:30",
        title: "Depart for CanevaWorld",
        description: "Drive to Lazise resort area (~30 min). Heat-friendly water park day.",
        locationName: "Lazise",
        lat: 45.4817,
        lng: 10.7936,
      },
      {
        id: "a19b",
        time: "10:00",
        title: "CanevaWorld Aqua Paradise",
        description: "Extreme slides, wave pools, lazy river — full day until ~15:00. Lunch in park ~13:00.",
        locationName: "Lazise",
        lat: 45.4817,
        lng: 10.7936,
        sourceAttractionId: "bank-caneva-aqua",
      },
      {
        id: "a19c",
        time: "15:30",
        title: "Peschiera del Garda",
        description: "Fortress walls, canals, and harbor stroll (~45 min) — same south-shore area.",
        locationName: "Peschiera del Garda",
        lat: 45.439,
        lng: 10.692,
        sourceAttractionId: "bank-peschiera",
      },
      {
        id: "a19d",
        time: "17:30",
        title: "Return to Villa Eunice",
        description: "Drive back to Monzambano.",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 8,
    date: "Jul 2 – Manerba Boat & Rocca Walk",
    activities: [
      {
        id: "a8boat",
        time: "09:30",
        title: "Manerba — Self-Drive Boat Rental (2 hrs)",
        description: "Rent a small family boat from Manerba marina (no license, up to 40 HP). Book ahead; swim stops on the lake.",
        locationName: "Manerba del Garda",
        lat: 45.492,
        lng: 10.6055,
        sourceAttractionId: "bank-manerba-boat",
      },
      {
        id: "a8lunch",
        time: "12:30",
        title: "Lunch — Manerba Waterfront",
        description: "Lido Azzurro or trattoria on the lake. Optional village harbor stroll after — see Day guide.",
        locationName: "Manerba del Garda",
        lat: 45.492,
        lng: 10.6055,
      },
      {
        id: "a8rocca",
        time: "14:00",
        title: "Rocca di Manerba Natural Park",
        description: "Clifftop trails and lake panoramas (~1.5–2 hr walk). Archaeological park on the same peninsula.",
        locationName: "Manerba del Garda",
        lat: 45.492,
        lng: 10.6055,
      },
      {
        id: "a8ret",
        time: "17:00",
        title: "Return to Villa Eunice",
        description: "Pre-packing for Milan transition tomorrow.",
        locationName: "Monzambano",
      },
    ],
  },
  {
    dayNumber: 9,
    date: "Jul 3 – Serravalle & Milan",
    activities: [
      {
        id: "a24",
        time: "09:30",
        title: "Check-out: Villa Eunice",
        description: "Check out of Villa Eunice. Ensure all items are packed, key returned, and loaded into the rental car.",
        locationName: "Monzambano",
      },
      {
        id: "a25",
        time: "10:00",
        title: "Serravalle Designer Outlet",
        description: "Drive ~1 hr 45 min. Shopping ~3 hrs — Nike, Adidas, Prada, Gucci outlets. Lunch at outlet food court.",
        locationName: "Serravalle Scrivia",
        lat: 44.6533,
        lng: 8.7847,
        sourceAttractionId: "bank-serravalle",
      },
      {
        id: "a26",
        time: "15:00",
        title: "Drive to Milan & Check-in",
        description: "Continue to Milan (~1 hr 15 min). ⚠️ ZTL / Area C: pay €7.50 entry fee if entering before 19:30 on Friday.",
        locationName: "Milan",
        lat: 45.464,
        lng: 9.19,
      },
      {
        id: "a27",
        time: "18:00",
        title: "Car Return – Centauro (Milano)",
        description: "Return rental car (Group E2) to Centauro at Via Copernico 28/30, 20125 Milano by 19:00 deadline. Fuel full.",
        locationName: "Via Copernico 28/30, Milan",
      },
      {
        id: "a28",
        time: "20:00",
        title: "Farewell Dinner in Milan",
        description: "Trattoria del Nuovo Macello (steak) or Spontini pizza. Navigli district for evening drinks.",
        locationName: "Milan",
        lat: 45.452,
        lng: 9.175,
        sourceAttractionId: "bank-dining-macello",
      },
    ],
  },
  {
    dayNumber: 10,
    date: "Jul 4 – Departure",
    activities: [
      {
        id: "a29",
        time: "08:30",
        title: "Check-out: Splendido Ultimo Piano",
        description: "Check out of the Milan apartment. Proceed to Milan Malpensa Airport (MXP) via taxi or Malpensa Express train (~50 min).",
        locationName: "Milan",
      },
      {
        id: "a30",
        time: "10:05",
        title: "Arrive Malpensa Airport – Check-in",
        description: "Arrive at MXP 3 hours before your flight to complete check-in, baggage drop, and security screening.",
        locationName: "Malpensa Airport",
      },
      {
        id: "a31",
        time: "13:05",
        title: "Flight 6403 Departs MXP → TLV",
        description: "Board flight 6403 departing MXP at 13:05. Scheduled arrival in Tel Aviv (TLV) at 18:00.",
        locationName: "Malpensa Airport",
      },
    ],
  },
];
