import type { SavedAttraction } from "@/types";

/** Curated Target Bank for Lake Garda base (Monzambano) — teens 15–18, Jun 2026 trip. */
export const LAKE_GARDA_TEEN_TARGET_BANK: SavedAttraction[] = [
  {
    id: "bank-gardaland",
    name: "Gardaland",
    description: "Italy's largest theme park — roller coasters, water rides, SEA LIFE aquarium. Mon Jun 29 weekday visit; arrive at opening.",
    locationName: "Castelnuovo del Garda",
    lat: 45.4542,
    lng: 10.7137,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-caneva-aqua",
    name: "CanevaWorld Aqua Paradise",
    description: "Water park with extreme slides and pools — scheduled Wed Jul 1; also Gardaland rain backup.",
    locationName: "Lazise",
    lat: 45.4817,
    lng: 10.7936,
    backupForDay: 5,
    alternateFor: "Gardaland Theme Park",
    planBReason: "Rain backup · water park",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-movieland",
    name: "Movieland Park",
    description: "Movie-themed rides and stunt shows — indoor rain backup near CanevaWorld resort.",
    locationName: "Lazise",
    lat: 45.483,
    lng: 10.794,
    backupForDay: 3,
    alternateFor: "Parco Giardino Sigurtà",
    planBReason: "Indoor rain backup · Lazise resort",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-monte-baldo",
    name: "Monte Baldo Cable Car",
    description: "Rotating cable car from Malcesine — panoramic views; Option B for Tue Jun 30 vs Verona.",
    locationName: "Malcesine",
    lat: 45.7634,
    lng: 10.8123,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-paragliding-malcesine",
    name: "Paragliding Tandem (Monte Baldo)",
    description: "Tandem flights from Monte Baldo — book ahead; minimum age typically 16 with guardian.",
    locationName: "Malcesine",
    lat: 45.816,
    lng: 10.852,
    backupForDay: 6,
    alternateFor: "Monte Baldo Cable Car",
    planBReason: "Cable car backup · book tandem flight",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-malcesine",
    name: "Malcesine",
    description: "Scaliger castle old town — combine with Monte Baldo cable car (Tue Jun 30 Option B).",
    locationName: "Malcesine",
    lat: 45.7628,
    lng: 10.8115,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-bergamo",
    name: "Bergamo Upper Town",
    description: "Funicular to the upper town — Old Square, cathedral, Venetian walls. Fri Jun 26 drive stop.",
    locationName: "Bergamo",
    lat: 45.704,
    lng: 9.662,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-castellaro",
    name: "Castellaro Lagusello",
    description: "Medieval hamlet and small lake loop — listed among Italy's most beautiful villages; Sat Jun 27 morning, 10 min from villa.",
    locationName: "Castellaro Lagusello",
    lat: 45.368,
    lng: 10.528,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-manerba-boat",
    name: "Manerba — Self-Drive Boat Rental",
    description: "Rent a small family boat from Manerba marina (no license, up to 40 HP). Sun Jun 28 — book ahead.",
    locationName: "Manerba del Garda",
    lat: 45.492,
    lng: 10.6055,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-vittoriale",
    name: "Vittoriale degli Italiani",
    description: "Eccentric poet's estate with a warship in the garden — quirky indoor backup west of the lake.",
    locationName: "Gardone Riviera",
    lat: 45.6236,
    lng: 10.5672,
    backupForDay: 3,
    alternateFor: "Borghetto sul Mincio",
    planBReason: "Museum backup · west lake",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-verona-arena",
    name: "Verona Arena",
    description: "1st-century Roman amphitheater — Tue Jun 30 Verona day trip (Option A).",
    locationName: "Verona",
    lat: 45.439,
    lng: 10.9944,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-sirmione-castle",
    name: "Sirmione — Scaligero Castle",
    description: "Medieval castle on the peninsula — Thu Jul 2 morning; keep visit short if teens prefer the spa.",
    locationName: "Sirmione",
    lat: 45.4928,
    lng: 10.6085,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-aquaria-spa",
    name: "Aquaria Thermal Spa",
    description: "Lakeside thermal pools — group booking Thu Jul 2 afternoon; book in advance.",
    locationName: "Sirmione",
    lat: 45.4903,
    lng: 10.6084,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-borghetto",
    name: "Borghetto sul Mincio",
    description: "Medieval watermill village — riverside walk ~1 hr. Sat Jun 27 nature day, 15 min from Monzambano.",
    locationName: "Borghetto sul Mincio",
    lat: 45.3533,
    lng: 10.7378,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-sigurta",
    name: "Parco Giardino Sigurtà",
    description: "Flat garden paths and flowers — gentle ~2 hr nature walk. Pair with Borghetto on Jun 27.",
    locationName: "Valeggio sul Mincio",
    lat: 45.3628,
    lng: 10.7347,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-peschiera",
    name: "Peschiera del Garda",
    description: "Fortress walls, canals, and harbor stroll — Wed Jul 1 after CanevaWorld (~45 min).",
    locationName: "Peschiera del Garda",
    lat: 45.439,
    lng: 10.692,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-serravalle",
    name: "Serravalle Designer Outlet",
    description: "Designer outlet shopping ~3 hrs — Fri Jul 3 en route to Milan.",
    locationName: "Serravalle Scrivia",
    lat: 44.6533,
    lng: 8.7847,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-ponte",
    name: "Trattoria del Ponte",
    description: "Welcome dinner — lake fish and local pasta in Monzambano. Fri Jun 26 evening.",
    locationName: "Monzambano",
    lat: 45.337,
    lng: 10.528,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-pace",
    name: "Ristorante Pace",
    description: "Desenzano waterfront — fresh lake fish and risotto. Backup south-shore lunch.",
    locationName: "Desenzano del Garda",
    lat: 45.4711,
    lng: 10.5358,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-pompiere",
    name: "Trattoria Al Pompiere",
    description: "Classic Verona grill — grilled chicken. Tue Jun 30 lunch.",
    locationName: "Verona",
    lat: 45.443,
    lng: 10.998,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-bersagliere",
    name: "Locanda al Bersagliere",
    description: "Sirmione castle area — lake-view lunch. Thu Jul 2.",
    locationName: "Sirmione",
    lat: 45.491,
    lng: 10.607,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-silenzio",
    name: "Taverna del Silenzio",
    description: "Famous Valeggio-style tortellini — book ahead! Sat Jun 27 lunch in Borghetto.",
    locationName: "Borghetto sul Mincio",
    lat: 45.353,
    lng: 10.735,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-malcesine",
    name: "Ristorante Vecchia Malcesine",
    description: "Pre-cable-car lunch in Malcesine old town. Tue Jun 30 Monte Baldo option.",
    locationName: "Malcesine",
    lat: 45.764,
    lng: 10.809,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-macello",
    name: "Trattoria del Nuovo Macello",
    description: "Milan farewell steak dinner. Fri Jul 3 evening. Alternative: Spontini pizza.",
    locationName: "Milan",
    lat: 45.452,
    lng: 9.175,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
];
