import type { SavedAttraction } from "@/types";

/** Curated Target Bank for Lake Garda base (Desenzano del Garda) — teens 15–18, Jun 2026 trip. */
export const LAKE_GARDA_TEEN_TARGET_BANK: SavedAttraction[] = [
  {
    id: "bank-gardaland",
    name: "Gardaland",
    description: "Italy's largest theme park — roller coasters, water rides, SEA LIFE aquarium. Mon Jun 29 weekday visit; ~20 min from Desenzano.",
    locationName: "Castelnuovo del Garda",
    lat: 45.4542,
    lng: 10.7137,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-caneva-aqua",
    name: "CanevaWorld Aqua Paradise",
    description: "Water park with extreme slides and pools — Wed Jul 1; ~25 min from Desenzano. Also Gardaland rain backup.",
    locationName: "Lazise",
    lat: 45.4817,
    lng: 10.7936,
    backupForDay: 5,
    alternateFor: "Gardaland Theme Park",
    planBReason: "Rain backup · water park",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-movieland",
    name: "Movieland Park",
    description: "Movie-themed rides and stunt shows — indoor rain backup near CanevaWorld resort.",
    locationName: "Lazise",
    lat: 45.483,
    lng: 10.794,
    backupForDay: 3,
    alternateFor: "Parco Giardino Sigurtà",
    planBReason: "Indoor rain backup · Lazise resort",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-monte-baldo",
    name: "Monte Baldo Cable Car",
    description: "Rotating cable car from Malcesine — panoramic views; Option B for Tue Jun 30 vs Verona.",
    locationName: "Malcesine",
    lat: 45.7634,
    lng: 10.8123,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-paragliding-malcesine",
    name: "Paragliding Tandem (Monte Baldo)",
    description: "Tandem flights from Monte Baldo — book ahead; minimum age typically 16 with guardian.",
    locationName: "Malcesine",
    lat: 45.816,
    lng: 10.852,
    backupForDay: 6,
    alternateFor: "Monte Baldo Cable Car",
    planBReason: "Cable car backup · book tandem flight",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-malcesine",
    name: "Malcesine",
    description: "Scaliger castle, Punto Panoramico, Palazzo dei Capitani — combine with Monte Baldo cable car (Tue Jun 30 Option B). Spritz at Bar Oasi.",
    locationName: "Malcesine",
    lat: 45.7628,
    lng: 10.8115,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-bergamo",
    name: "Bergamo Upper Town",
    description: "Funicular to the upper town — Old Square, cathedral, Venetian walls. Fri Jun 26 drive stop.",
    locationName: "Bergamo",
    lat: 45.704,
    lng: 9.662,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-castellaro",
    name: "Castellaro Lagusello",
    description: "Medieval hamlet and small lake loop — listed among Italy's most beautiful villages; Sat Jun 27 morning, ~35 min from Desenzano.",
    locationName: "Castellaro Lagusello",
    lat: 45.368,
    lng: 10.528,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-manerba-boat",
    name: "Manerba — Self-Drive Boat Rental",
    description: "Rent a small family boat from Manerba marina (no license, up to 40 HP). Sun Jun 28 — ~40 min from Desenzano, book ahead.",
    locationName: "Manerba del Garda",
    lat: 45.492,
    lng: 10.6055,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-vittoriale",
    name: "Vittoriale degli Italiani",
    description: "Eccentric poet's estate with a warship in the garden — quirky indoor backup west of the lake.",
    locationName: "Gardone Riviera",
    lat: 45.6236,
    lng: 10.5672,
    backupForDay: 3,
    alternateFor: "Borghetto sul Mincio",
    planBReason: "Museum backup · west lake",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-verona-arena",
    name: "Verona Arena",
    description: "1st-century Roman amphitheater — Tue Jun 30 Verona day trip (Option A).",
    locationName: "Verona",
    lat: 45.439,
    lng: 10.9944,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-sirmione-castle",
    name: "Sirmione — Scaligero Castle",
    description: "Medieval castle on the peninsula — Thu Jul 2 morning; keep visit short if teens prefer the spa.",
    locationName: "Sirmione",
    lat: 45.4928,
    lng: 10.6085,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-aquaria-spa",
    name: "Aquaria Thermal Spa",
    description: "Lakeside thermal pools — group booking Thu Jul 2 afternoon; book in advance.",
    locationName: "Sirmione",
    lat: 45.4903,
    lng: 10.6084,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-borghetto",
    name: "Borghetto sul Mincio",
    description: "Medieval watermill village — riverside walk ~1 hr. Sat Jun 27 nature day, ~35 min from Desenzano.",
    locationName: "Borghetto sul Mincio",
    lat: 45.3533,
    lng: 10.7378,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-sigurta",
    name: "Parco Giardino Sigurtà",
    description: "Flat garden paths and flowers — gentle ~2 hr nature walk. Pair with Borghetto on Jun 27.",
    locationName: "Valeggio sul Mincio",
    lat: 45.3628,
    lng: 10.7347,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-peschiera",
    name: "Peschiera del Garda",
    description: "Fortress walls (UNESCO), canals, stilt houses, Mincio bike path — Wed Jul 1 after CanevaWorld (~45 min). Ottella Winery nearby.",
    locationName: "Peschiera del Garda",
    lat: 45.439,
    lng: 10.692,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-serravalle",
    name: "Serravalle Designer Outlet",
    description: "Designer outlet shopping ~3 hrs — Fri Jul 3 en route to Milan.",
    locationName: "Serravalle Scrivia",
    lat: 44.6533,
    lng: 8.7847,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-ponte",
    name: "Trattoria del Ponte",
    description: "Lakeside trattoria on the Mincio — lake fish and tortellini. Day 3 Borghetto backup if you skip the main valley loop.",
    locationName: "Borghetto sul Mincio",
    lat: 45.337,
    lng: 10.528,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-pace",
    name: "Ristorante Pace",
    description: "Desenzano waterfront — fresh lake fish and risotto. Welcome dinner Fri Jun 26 evening.",
    locationName: "Desenzano del Garda",
    lat: 45.4711,
    lng: 10.5358,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-pompiere",
    name: "Trattoria Al Pompiere",
    description: "Classic Verona grill — grilled chicken. Tue Jun 30 lunch.",
    locationName: "Verona",
    lat: 45.443,
    lng: 10.998,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-bersagliere",
    name: "Locanda al Bersagliere",
    description: "Sirmione castle area — lake-view lunch. Thu Jul 2.",
    locationName: "Sirmione",
    lat: 45.491,
    lng: 10.607,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-silenzio",
    name: "Taverna del Silenzio",
    description: "Famous Valeggio-style tortellini — book ahead! Sat Jun 27 lunch in Borghetto.",
    locationName: "Borghetto sul Mincio",
    lat: 45.353,
    lng: 10.735,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-malcesine",
    name: "Ristorante Vecchia Malcesine",
    description: "Pre-cable-car lunch in Malcesine old town. Tue Jun 30 Monte Baldo option.",
    locationName: "Malcesine",
    lat: 45.764,
    lng: 10.809,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-macello",
    name: "Trattoria del Nuovo Macello",
    description: "Milan farewell steak dinner. Fri Jul 3 evening. Alternative: Spontini pizza.",
    locationName: "Milan",
    lat: 45.452,
    lng: 9.175,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-bardolino",
    name: "Bardolino",
    description: "Lakeside wine town — promenade, walk to Garda, winery tastings, La Loggia Rambaldi. Day 7 Option B (~25 min from Desenzano).",
    locationName: "Bardolino",
    lat: 45.5506,
    lng: 10.7254,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-garda-village",
    name: "Garda",
    description: "Classic south-lake harbour village — lungolago walk, Punta San Vigilio nearby. Day 7 Option B (~30 min from Desenzano).",
    locationName: "Garda",
    lat: 45.5811,
    lng: 10.7094,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-lazise-town",
    name: "Lazise Historic Centre",
    description: "Medieval walls, Scaliger castle, Wednesday market, Cristallo aperitivo — same resort area as CanevaWorld. Day 7 Option A (optional) or Option B.",
    locationName: "Lazise",
    lat: 45.4817,
    lng: 10.7936,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-lonato-rocca",
    name: "Rocca di Lonato",
    description: "Hilltop fortress with lake panoramas — quick stop ~15 min from Desenzano. Optional spare evening or rainy-day castle visit.",
    locationName: "Lonato del Garda",
    lat: 45.4608,
    lng: 10.4825,
    backupForDay: 4,
    alternateFor: "Manerba Rocca Natural Park",
    planBReason: "Closer castle views if Manerba hike is rained out",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-moniga",
    name: "Moniga del Garda",
    description: "Castle ruins and lake beaches — teen swim option on the southwest shore (~15 min from Desenzano).",
    locationName: "Moniga del Garda",
    lat: 45.524,
    lng: 10.534,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-limone",
    name: "Limone sul Garda",
    description: "Limonaia del Castel, cliffside cycle path, Porto Vecchio lemon sorbet — west shore (~1 hr from Desenzano). Optional long day or Monte Baldo add-on.",
    locationName: "Limone sul Garda",
    lat: 45.813,
    lng: 10.791,
    backupForDay: 6,
    alternateFor: "Monte Baldo Cable Car",
    planBReason: "Scenic west-shore village if cable car is closed",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-navigarda",
    name: "Navigarda Lake Ferry",
    description: "Hop-on hop-off ferry linking Desenzano, Sirmione, Peschiera, and north-lake towns — scenic summer alternative to driving.",
    locationName: "Desenzano del Garda",
    lat: 45.4711,
    lng: 10.5358,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-tibetan-bridge",
    name: "Tibetan Bridge — Crero (Torri del Benaco)",
    description:
      "Ponte Tibetano suspension bridge over Val Vanzana — 35 m long, ~42 m high. Easy–moderate 1.5–2 hr loop from Crero or Pai di Sopra (CAI 38/39). East shore ~50 min from Desenzano.",
    locationName: "Torri del Benaco",
    lat: 45.611,
    lng: 10.686,
    backupForDay: 4,
    alternateFor: "Manerba — Self-Drive Boat Rental",
    planBReason: "Gorge hike swap · teens thrill factor",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-paganella-traverse",
    name: "Paganella — Canfedin & Monte Gazza traverse",
    description:
      "Medium ridge hike from Cima Paganella (cable car from Andalo): sentiero 602, Cima Canfedin, Monte Gazza, Malga di Covelo. 5–5.5 hr; Brenta Dolomites & Lake Garda panoramas. Full day — ~2 hr drive from Desenzano via Molveno.",
    locationName: "Molveno",
    lat: 46.144,
    lng: 10.925,
    backupForDay: 4,
    alternateFor: "Manerba — Self-Drive Boat Rental",
    planBReason: "Ambitious mountain day · skip lake boat",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-torri-benaco",
    name: "Torri del Benaco",
    description: "East-shore port village with Scaliger castle — gateway to the Tibetan Bridge hike (~50 min from Desenzano).",
    locationName: "Torri del Benaco",
    lat: 45.61,
    lng: 10.686,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-salo",
    name: "Salò",
    description: "West-shore promenade — one of the lake's longest lungolago walks, MU.SA museum, Pasticceria Vassalli. ~45 min from Desenzano — optional spare afternoon.",
    locationName: "Salò",
    lat: 45.606,
    lng: 10.521,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-padenghe-beach",
    name: "Padenghe sul Garda — pebble beach",
    description: "Small tranquil pebble beach — picnic-friendly swim spot on the southwest shore (~20 min from Desenzano).",
    locationName: "Padenghe sul Garda",
    lat: 45.507,
    lng: 10.539,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-ottella-winery",
    name: "Ottella Winery",
    description: "Lugana wine tastings near Peschiera — indoor tasting room, ideal on rainy days (~10 min from fortress walls).",
    locationName: "Peschiera del Garda",
    lat: 45.428,
    lng: 10.698,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-isola-garda",
    name: "Isola del Garda",
    description: "Private island villa boat tours May–October — book from ports near Sirmione, Bardolino, or Salò.",
    locationName: "Isola del Garda",
    lat: 45.586,
    lng: 10.595,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-olive-oil-museum",
    name: "Museo dell'Olio (Cisano)",
    description: "Olive Oil Museum near Bardolino — short cultural stop on a village day (~20 min visit).",
    locationName: "Cisano",
    lat: 45.542,
    lng: 10.732,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-desenzano",
    name: "Desenzano del Garda",
    description: "Base town — Tuesday market, harbour promenade, Archaeological Museum, Vineria Porto Vecchio, welcome dinner at Pace.",
    locationName: "Desenzano del Garda",
    lat: 45.4711,
    lng: 10.5358,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
];
