import type { SavedAttraction } from "@/types";

/** Curated Target Bank for Lake Garda base (Monzambano) — teens 15–18, Jun 2026 trip. */
export const LAKE_GARDA_TEEN_TARGET_BANK: SavedAttraction[] = [
  {
    id: "bank-gardaland",
    name: "Gardaland",
    description: "Italy's largest theme park — roller coasters, water rides, SEA LIFE aquarium. Full day; arrive at opening.",
    locationName: "Castelnuovo del Garda",
    lat: 45.4542,
    lng: 10.7137,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-caneva-aqua",
    name: "CanevaWorld Aqua Paradise",
    description: "Water park with extreme slides and pools — ideal hot-day alternative to Gardaland.",
    locationName: "Lazise",
    lat: 45.4817,
    lng: 10.7936,
    backupForDay: 3,
    alternateFor: "Self-Drive Boat Rental",
    planBReason: "Rain backup · same area",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-movieland",
    name: "Movieland Park",
    description: "Movie-themed rides and stunt shows — same resort area as CanevaWorld.",
    locationName: "Lazise",
    lat: 45.483,
    lng: 10.794,
    alternateFor: "Gardaland Theme Park",
    planBReason: "Indoor backup · Caneva park",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-jungle-adventure",
    name: "Jungle Adventure Park",
    description: "Tree-top ropes and zip lines near Gardaland — good half-day add-on.",
    locationName: "Lazise",
    lat: 45.503,
    lng: 10.726,
    backupForDay: 3,
    planBReason: "Active backup · near Desenzano",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-rimbalzello",
    name: "Rimbalzello Adventure Park",
    description: "Lake-view adventure park — Tibetan bridges, zip lines, treetop courses.",
    locationName: "Manerba del Garda",
    lat: 45.492,
    lng: 10.6055,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-monte-baldo",
    name: "Monte Baldo Cable Car",
    description: "Rotating cable car from Malcesine — panoramic views; gateway to hiking and paragliding.",
    locationName: "Malcesine",
    lat: 45.7634,
    lng: 10.8123,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-paragliding-malcesine",
    name: "Paragliding Tandem (Monte Baldo)",
    description: "Tandem flights from Monte Baldo — book ahead; minimum age typically 16 with guardian.",
    locationName: "Malcesine",
    lat: 45.816,
    lng: 10.852,
    backupForDay: 7,
    alternateFor: "Monte Baldo Cable Car",
    planBReason: "Cable car backup · book tandem flight",
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-malcesine",
    name: "Malcesine",
    description: "Scaliger castle old town — combine with Monte Baldo cable car or lake ferry.",
    locationName: "Malcesine",
    lat: 45.7628,
    lng: 10.8115,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-riva-water-sports",
    name: "Riva del Garda — SUP & Water Sports",
    description: "SUP, kayak, wakeboard rentals — active lake day at the north shore.",
    locationName: "Riva del Garda",
    lat: 45.8858,
    lng: 10.8411,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-torbole-windsurf",
    name: "Torbole — Windsurfing & Sailing",
    description: "Wind capital of Lake Garda — lessons and rentals for windsurf and sailing.",
    locationName: "Torbole sul Garda",
    lat: 45.8708,
    lng: 10.8756,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-desenzano-boat",
    name: "Desenzano — Self-Drive Boat Rental",
    description: "Rent a small boat (no license, up to 40 HP) — more engaging than a guided tour.",
    locationName: "Desenzano del Garda",
    lat: 45.4711,
    lng: 10.5358,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-natura-viva",
    name: "Natura Viva Safari Park",
    description: "Safari park and zoo near Verona — strong appeal for teens; ~45 min from Monzambano.",
    locationName: "Bussolengo",
    lat: 45.4431,
    lng: 10.8706,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-vittoriale",
    name: "Vittoriale degli Italiani",
    description: "Eccentric poet's estate with a warship in the garden — quirky hit with older teens.",
    locationName: "Gardone Riviera",
    lat: 45.6236,
    lng: 10.5672,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-verona-arena",
    name: "Verona Arena",
    description: "1st-century Roman amphitheater — already scheduled Jun 28 day trip.",
    locationName: "Verona",
    lat: 45.439,
    lng: 10.9944,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-sirmione-castle",
    name: "Sirmione — Scaligero Castle",
    description: "Medieval castle on the peninsula — keep visit short if teens prefer the spa.",
    locationName: "Sirmione",
    lat: 45.4928,
    lng: 10.6085,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-aquaria-spa",
    name: "Aquaria Thermal Spa",
    description: "Lakeside thermal pools — group booking Jun 29; book in advance.",
    locationName: "Sirmione",
    lat: 45.4903,
    lng: 10.6084,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-borghetto",
    name: "Borghetto sul Mincio",
    description: "Medieval watermill village — riverside walk ~1 hr. Jul 2 nature day, 15 min from Monzambano.",
    locationName: "Borghetto sul Mincio",
    lat: 45.3533,
    lng: 10.7378,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-sigurta",
    name: "Parco Giardino Sigurtà",
    description: "Flat garden paths and flowers — gentle ~2 hr nature walk. Pair with Borghetto.",
    locationName: "Valeggio sul Mincio",
    lat: 45.3628,
    lng: 10.7347,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-serravalle",
    name: "Serravalle Designer Outlet",
    description: "Designer outlet shopping ~3 hrs — Jul 3 en route to Milan.",
    locationName: "Serravalle Scrivia",
    lat: 44.6533,
    lng: 8.7847,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-ponte",
    name: "Trattoria del Ponte",
    description: "Welcome dinner — lake fish and local pasta in Monzambano. Jun 26 evening.",
    locationName: "Monzambano",
    lat: 45.337,
    lng: 10.528,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-pace",
    name: "Ristorante Pace",
    description: "Desenzano waterfront — fresh lake fish and risotto. Jun 27 lunch.",
    locationName: "Desenzano del Garda",
    lat: 45.4711,
    lng: 10.5358,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-pompiere",
    name: "Trattoria Al Pompiere",
    description: "Classic Verona grill — pollo alla griglia. Jun 28 lunch.",
    locationName: "Verona",
    lat: 45.443,
    lng: 10.998,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-bersagliere",
    name: "Locanda al Bersagliere",
    description: "Sirmione castle area — lake-view lunch. Jun 29.",
    locationName: "Sirmione",
    lat: 45.491,
    lng: 10.607,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-silenzio",
    name: "Taverna del Silenzio",
    description: "Famous Tortellini di Valeggio — book ahead! Jul 2 lunch in Borghetto.",
    locationName: "Borghetto sul Mincio",
    lat: 45.353,
    lng: 10.735,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-malcesine",
    name: "Ristorante Vecchia Malcesine",
    description: "Pre-cable-car lunch in Malcesine old town. Jul 1 Monte Baldo day.",
    locationName: "Malcesine",
    lat: 45.764,
    lng: 10.809,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
  {
    id: "bank-dining-macello",
    name: "Trattoria del Nuovo Macello",
    description: "Milan farewell steak dinner. Jul 3 evening. Alternative: Spontini pizza.",
    locationName: "Milan",
    lat: 45.452,
    lng: 9.175,
    upvotes: [],
    downvotes: [],
    createdBy: "TripiAgent",
  },
];
