import { NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

/**
 * Simple debug endpoint to verify that the GEMINI_API_KEY works and that the
 * Gemini SDK can generate a response. Returns the raw text generated by the
 * model for the prompt "Hello".
 */
export async function GET() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ error: 'Missing GEMINI_API_KEY' }, { status: 500 });
  }

  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    const modelName = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
    const model = genAI.getGenerativeModel({ model: modelName });

    const result = await model.generateContent('Hello');
    const responseText = result.response?.text() ?? '';

    return NextResponse.json({ response: responseText });
  } catch (error) {
    console.error('Gemini ping error:', error);
    // Provide more detail for debugging
    const msg = error instanceof Error ? error.message : String(error);
    return NextResponse.json({ error: 'Gemini request failed', details: msg }, { status: 500 });
  }
}
